# 02 Raw Data Profiling
**Project:** Retailmart Finance Analytics  
**Phase:** Examine the shape, columns, missing values, and data types of extracted raw data.

---

### 1. Setup & Imports
We must add the parent directory to the system path so Python can locate the custom `src` modules.

In [1]:
import sys
import os
import pandas as pd
import numpy as np

# Add root directory to python path
sys.path.append(os.path.abspath(os.path.join('..')))

# Import custom configurations and utilities
from src.config.config import config
from src.database.connection import db_connector
from src.utils.logger import setup_logger
from src.utils.helpers import save_dataframe

logger = setup_logger(os.path.splitext(os.path.basename('__file__'))[0])
logger.info('Notebook setup and imports loaded successfully.')

[2026-07-17 11:35:06] [INFO] [config.py:16] Loaded environment configuration from: E:\SQL ACCIO JOB\Cross functional dashboard\.env

[2026-07-17 11:35:06] [INFO] [connection.py:42] SQLAlchemy Database Engine initialized successfully.

[2026-07-17 11:35:06] [INFO] [4206973462.py:16] Notebook setup and imports loaded successfully.

### 2. Load Raw CSV Files
Placeholder for load raw csv files steps.

In [2]:
import glob
import os

# Find all raw CSV files we extracted
raw_files = glob.glob("../data/raw/*.csv")
print(f"Found {len(raw_files)} raw files to profile:\n")

# Load into a dictionary: key is the clean filename, value is the DataFrame
dfs = {}
for file in raw_files:
    name = os.path.splitext(os.path.basename(file))[0]
    dfs[name] = pd.read_csv(file)
    print(f" - Loaded: {name} (Shape: {dfs[name].shape})")

Found 18 raw files to profile:

 - Loaded: customer_customers (Shape: (5000, 19))
 - Loaded: dealer_dealers (Shape: (200, 16))
 - Loaded: dealer_network_dealer_commissions (Shape: (3000, 9))
 - Loaded: dealer_network_dealer_targets (Shape: (4800, 8))
 - Loaded: dealer_network_regional_offices (Shape: (20, 4))
 - Loaded: finance_accounting_dealer_payouts (Shape: (2500, 7))
 - Loaded: finance_accounting_gl_accounts (Shape: (80, 6))

 - Loaded: finance_accounting_ledger_entries (Shape: (15000, 10))
 - Loaded: finance_accounting_tax_records (Shape: (7000, 8))
 - Loaded: location_reference_cities (Shape: (200, 7))
 - Loaded: location_reference_states (Shape: (36, 6))
 - Loaded: pricing_management_price_master (Shape: (1440, 10))
 - Loaded: product_management_vehicle_models (Shape: (25, 9))
 - Loaded: product_management_vehicle_variants (Shape: (96, 11))
 - Loaded: sales_transaction_invoices (Shape: (7000, 14))
 - Loaded: sales_transaction_orders (Shape: (7000, 16))

 - Loaded: sales_transaction_order_items (Shape: (7500, 12))
 - Loaded: sales_transaction_payments (Shape: (8000, 11))

### 3. Dataset Shapes & Info
Placeholder for dataset shapes & info steps.

In [3]:
# Create a summary table showing row counts, column counts, and memory usage
shape_summary = []
for name, df in dfs.items():
    shape_summary.append({
        "Dataset Name": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Memory Usage (KB)": round(df.memory_usage(deep=True).sum() / 1024, 2)
    })

df_summary = pd.DataFrame(shape_summary).sort_values(by="Rows", ascending=False)
df_summary

                           Dataset Name   Rows  Columns  Memory Usage (KB)
7     finance_accounting_ledger_entries  15000       10            5590.42
17           sales_transaction_payments   8000       11            3052.58
16        sales_transaction_order_items   7500       12            1527.37
14           sales_transaction_invoices   7000       14            2141.62
15             sales_transaction_orders   7000       16            3013.86
8        finance_accounting_tax_records   7000        8            1388.91
0                    customer_customers   5000       19            4320.64
3         dealer_network_dealer_targets   4800        8             300.13
2     dealer_network_dealer_commissions   3000        9             631.79
5     finance_accounting_dealer_payouts   2500        7             511.20
11      pricing_management_price_master   1440       10             174.50
1                        dealer_dealers    200       16             151.58
9             location_reference_cities    200        7              29.78
13  product_management_vehicle_variants     96       11              37.26
6        finance_accounting_gl_accounts     80        6              16.48
10            location_reference_states     36        6               8.35
12    product_management_vehicle_models     25        9               7.12
4       dealer_network_regional_offices     20        4               2.84

### 4. Missing Value Analysis
Placeholder for missing value analysis steps.

In [4]:
# Identify columns containing null/missing values across all datasets
missing_summary = []
for name, df in dfs.items():
    null_counts = df.isnull().sum()
    null_cols = null_counts[null_counts > 0]
    
    for col, count in null_cols.items():
        missing_summary.append({
            "Dataset": name,
            "Column": col,
            "Missing Rows": count,
            "Percentage (%)": round((count / len(df)) * 100, 2)
        })
        
df_missing = pd.DataFrame(missing_summary)
if df_missing.empty:
    print("No missing values found in any dataset!")
else:
    print(f"Found {len(missing_summary)} columns with missing values across datasets:\n")
    display(df_missing.sort_values(by="Percentage (%)", ascending=False))

Found 9 columns with missing values across datasets:

,Dataset,Column,Missing Rows,Percentage (%)
5,pricing_management_price_master,effective_to,1440,100.00
6,product_management_vehicle_models,end_of_life_date,19,76.00
1,customer_customers,alternate_phone,3062,61.24
7,sales_transaction_orders,discount_id,2848,40.69
4,finance_accounting_gl_accounts,parent_account_id,20,25.00
3,dealer_network_dealer_commissions,payout_date,602,20.07
8,sales_transaction_orders,finance_provider,1033,14.76
0,customer_customers,email,110,2.20
2,dealer_dealers,gst_number,2,1.00

### 5. Check Data Types and Anomalies
Placeholder for check data types and anomalies steps.

In [5]:
# Profile the main transactions table for data types, distributions, and possible anomalies
orders_df = dfs.get("sales_transaction_orders")
if orders_df is not None:
    print("--- Profiling Core Table: sales_transaction_orders ---\n")
    
    print("1. Data Types and Sample:")
    display(orders_df.info())
    
    print("\n2. Summary Statistics for Numeric Fields:")
    display(orders_df.describe())
    
    print("\n3. Checking for Negative Numeric Anomalies:")
    neg_net = orders_df[orders_df["net_amount"] < 0]
    neg_total = orders_df[orders_df["total_amount"] < 0]
    print(f" - Orders with negative net_amount: {len(neg_net)}")
    print(f" - Orders with negative total_amount: {len(neg_total)}")
    
    print("\n4. Check Unique Counts & Distribution of Payment Modes:")
    print(orders_df["payment_mode"].value_counts(dropna=False))
else:
    print("Core orders dataset not found. Make sure sales_transaction_orders.csv exists.")

--- Profiling Core Table: sales_transaction_orders ---

1. Data Types and Sample:
<class 'pandas.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            7000 non-null   int64
 1   order_number        7000 non-null   str
 2   booking_id          7000 non-null   int64
 3   customer_id         7000 non-null   int64
 4   dealer_id           7000 non-null   int64
 5   order_date          7000 non-null   str
 6   order_status        7000 non-null   str
 7   sales_executive_id  7000 non-null   int64
 8   discount_id         4152 non-null   float64
 9   total_amount        7000 non-null   float64
 10  discount_amount     7000 non-null   float64
 11  tax_amount          7000 non-null   float64
 12  net_amount          7000 non-null   float64
 13  payment_mode        7000 non-null   str
 14  finance_provider    5967 non-null   str
 15  created_at          7000 non-null   str
dtypes: float64(5), int64(5), str(6)
memory usage: 875.1 KB

None

2. Summary Statistics for Numeric Fields:

,order_id,booking_id,customer_id,dealer_id,sales_executive_id,discount_id,total_amount,discount_amount,tax_amount,net_amount
count,7000.000000,7000.000000,7000.000000,7000.000000,7000.000000,4152.000000,7.000000e+03,7000.000000,7000.000000,7.000000e+03
mean,3500.500000,3365.221286,2493.647857,100.593571,501.916571,15.252408,1.449684e+06,50761.256434,391698.370219,1.790621e+06
std,2020.870275,2406.421889,1439.405377,58.087504,285.271748,8.763075,6.055025e+05,38128.175056,163777.697116,7.486980e+05
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.002470e+05,-28293.600000,104843.420000,4.792842e+05
25%,1750.750000,1198.000000,1238.000000,51.000000,255.000000,8.000000,9.226642e+05,20564.517500,250005.472500,1.142882e+06
50%,3500.500000,2948.000000,2491.500000,99.000000,505.000000,15.000000,1.449212e+06,41679.035000,391210.470000,1.788391e+06
75%,5250.250000,5445.250000,3713.750000,152.000000,745.000000,23.000000,1.975486e+06,73746.122500,533059.090000,2.436842e+06
max,7000.000000,8000.000000,4999.000000,200.000000,1000.000000,30.000000,2.499759e+06,173397.700000,697021.260000,3.186383e+06

3. Checking for Negative Numeric Anomalies:
 - Orders with negative net_amount: 0
 - Orders with negative total_amount: 0

4. Check Unique Counts & Distribution of Payment Modes:
payment_mode
Lease    1795
Loan     1761
Cash     1739
EMI      1705
Name: count, dtype: int64